<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Dzikra-Shanum" failures="1" tests="2" name="test1" time="0.133" errors="0" timestamp="2022-10-07T18:22:47 WIB">
  <testcase classname="com.juaracoding.testng.GroupTestExample" name="testPrintMessage" time="0.016"/>
  <testcase classname="com.juaracoding.testng.GroupTestExample" name="testingExitMessage" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [www..com] but found [www.tutorialspoint.com]">
      <![CDATA[java.lang.AssertionError: expected [www..com] but found [www.tutorialspoint.com]
at com.juaracoding.testng.GroupTestExample.testingExitMessage(GroupTestExample.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testingExitMessage -->
  <testcase classname="com.juaracoding.testng.GroupTestExample" name="testSalutationMessage" time="0.0">
    <ignored/>
  </testcase> <!-- testSalutationMessage -->
</testsuite> <!-- test1 -->
